### ISSUE TITLE
which git repo to use?

### ISSUE THREAD

**Issue by joe9** [bkubicek/pcb2gcode#1]
Hello,

git://pcb2gcode.git.sourceforge.net/gitroot/pcb2gcode/pcb2gcode repo does not have some of the commits from this (github) repo.

Is this github repo is better/later than the sourceforge one? Any thoughts, please?

Thanks
Joe

**Comment by phragment** [comment]
I endorse https://github.com/patkan/pcb2gcode since it is currently the most advanced and active fork.
